AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Bellflower: CFN Template to create am IAM Role for Lambda Function and State Machine

Metadata:
  TemplateName: iam-role-stack.yaml
  TemplateType: Lambda Function
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Bellflower
  Modification History:
    - 1.0.0  - Oct 03, 2023   -- Initial Version
  Resources: 
    - Resources
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
        - ProjectName
        - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
      - StackName
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyId
    #################################### Services Referred in the IAM Role #########################
    - Label:
        default: "Service Names"
      Parameters:
      - ProcessingLambdaFunctionName
      - IntegrationLambdaFunctionName
      - LambdaExecutionRoleName
      - LambdaExecutionPolicyName
      - StepFunctionExecutionRoleName
      - StepFunctionExecutionPolicyName
      - SQSQueueName
      - SNSTopicName
      - S3BucketName
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## Services Referred in the IAM Role #########################
      ProcessingLambdaFunctionName: 
        default: "Processing Lammba Function Name."
      IntegrationLambdaFunctionName: 
        default: "Processing Lammba Function Name."
      LambdaExecutionRoleName: 
        default: "Lambda Function Execution Role Name."
      LambdaExecutionPolicyName:
        default: "Lambda Function Execution Policy Name."
      StepFunctionExecutionRoleName: 
        default: "Step Function Execution Role Name."
      StepFunctionExecutionPolicyName: 
        default: "Step Function Execution Policy Name."
      SQSQueueName:  
        default: "The Base Name Of The SQS Queue."
      SNSTopicName: 
        default: "The Name Of The SNS Topic to publish success / failure message."
      S3BucketName: 
        default: "The Name Of The S3 Integration Bucket."
      StepFunctionName: 
        default: "The Name Of The Step Function"
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: project
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  StackName:
    Default: ""
    Description: "The name of the stack which created the resource"
    Type: String  
  ###################################### KMS #######################################################
  KmsMasterKeyId:
    Default: "arn:aws:kms:us-east-1:807724355529:key/e4c733c5-9fbe-4a90-bda1-6f0362bc9b89"
    Description: "The KMS Key Id Used For Encryption."
    Type: String
    MinLength: 75
    MaxLength: 75
    AllowedPattern: "[a-z0-9-/:]*"
    ConstraintDescription: "The length of the KMS Key Id should be 75 and must be a valid KMS Key Arn."
  ###################################### Lambda Function ###########################################
  ProcessingLambdaFunctionName:
    Default: some-lambda-function-name
    Description: Processing Lambda Function Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  IntegrationLambdaFunctionName:
    Default: some-other-lambda-function-name
    Description: Integration Lambda Function Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  LambdaExecutionRoleName:
    Default: Lambda-Function-Role-Name
    Description: Lambda Function Execution Role Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  LambdaExecutionPolicyName:
    Default: Lambda-Function-Policy-Name
    Description: Lambda Function Execution Policy Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  StepFunctionExecutionRoleName:
    Default: Step-Function-Role-Name
    Description: Step Function Execution Role Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  StepFunctionExecutionPolicyName:
    Default: Step-Function-Policy-Name
    Description: Step Function Execution Policy Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  SQSQueueName:
    Default: some-sqs-queue-name
    Type: String
    Description: "SQS Queue Name."
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9/-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric character.
  SNSTopicName: 
    Default: some-sns-topic-name
    Type: String
    Description: "SQS Queue Name."
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9/-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric character.
  S3BucketName: 
    Default: some-s3-bucket-name
    Description: "The S3 Bucket Base Name for the source data, the instance and region will be added as suffix by the template."
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: The length should be between 3 and 63, must contain only lowercase letter,numbers,dash, dot and should start with a letter.
  StepFunctionName:
    Default: step-function-name
    Description: Step Function Execution Policy Name
    Type: String
    MinLength: 10
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 5 and 60, must contain only lowecase letters, numbers and hyphen (-).
Resources:

  ###################################### Lambda Execution Role #####################################
  BellflowerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${LambdaExecutionRoleName}${CiBuild}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${LambdaExecutionPolicyName}${CiBuild}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowCloudWatchLogStream
              Effect: Allow
              Action: 
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: 
                - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ProcessingLambdaFunctionName}${CiBuild}:*'
                - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${IntegrationLambdaFunctionName}${CiBuild}:*'
            - Sid: AllowReceiveAndDeleteMessageFromSQS
              Effect: Allow
              Action: 
                - 'sqs:ReceiveMessage'
                - 'sqs:DeleteMessage'
                - 'sqs:GetQueueAttributes'
              Resource: !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${SQSQueueName}${CiBuild}'
            - Sid: AllowKMSDecrypt
              Effect: Allow
              Action: 
                - kms:Decrypt
                - kms:GenerateDataKey
                - kms:GenerateDataKeyPair
              Resource: !Ref KmsMasterKeyId
            - Sid: AllowReadWriteOnS3Bucket
              Effect: Allow
              Action: 
                - s3:PutObject
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub 'arn:${AWS::Partition}:s3:::${S3BucketName}${CiBuild}/outbound/*'
            - Sid: AllowReadFromS3InboundFolder
              Effect: Allow
              Action: 
                - s3:ReadObject
              Resource: !Sub 'arn:${AWS::Partition}:s3:::${S3BucketName}${CiBuild}/inbound/*'
            - Sid: AllowSendTaskStatus
              Effect: Allow
              Action: 
                - states:SendTaskSuccess
              Resource: !Sub 'arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StepFunctionName}${CiBuild}'
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key:  Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
      - Key: StackName
        Value: !Ref StackName
  ###################################### State Machine Execution Role ##############################
  BellflowerStepFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref StepFunctionExecutionRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - states.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
      Policies:
        - PolicyName: !Ref StepFunctionExecutionPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowSendMessageToSQS
              Effect: Allow
              Action: 
                - sqs:SendMessage
              Resource: !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${SQSQueueName}'
            - Sid: AllowKMSDecrypt
              Effect: Allow
              Action: 
                - kms:Decrypt
                - kms:GenerateDataKey
                - kms:GenerateDataKeyPair
              Resource: !Ref KmsMasterKeyId
            - Sid: AllowCloudWatchLogStream
              Effect: Allow
              Action: 
              - logs:CreateLogDelivery
              - logs:CreateLogStream
              - logs:GetLogDelivery
              - logs:UpdateLogDelivery
              - logs:DeleteLogDelivery
              - logs:ListLogDeliveries
              - logs:PutLogEvents
              - logs:PutResourcePolicy
              - logs:DescribeResourcePolicies
              - logs:DescribeLogGroups
              Resource: "*"
            - Sid: AllowPublishToSNSTpoic
              Effect: Allow
              Action: 
              - sns:Publish
              Resource: !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${SNSTopicName}'
      Tags:
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key:  Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
      - Key: StackName
        Value: !Ref StackName
Outputs:
  LambdaExecutionRoleArn:
    Description: The Arn of the Lambda Execution Role
    Value: !GetAtt BellflowerLambdaExecutionRole.Arn
  StepFunctionExecutionRoleArn:
    Description: The Arn of the Step Function Execution Role
    Value: !GetAtt BellflowerStepFunctionExecutionRole.Arn
