AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Bellflower: CFN Template To Create A S3 Table With Or Without A Folder. 

Metadata:
  TemplateName: s3-stack.yaml
  TemplateType: S3 Bucket
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Bellflower
  Modification History:
    - 1.0.0  - Oct 03, 2023   -- Initial Version
  Resources: 
    - Resources
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label:
        default: "Project Name And Environment:"
      Parameters:
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
      - StackName
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyAlias
    #################################### KMS Key ###################################################
    - Label:
        default: "S3 Configuration:"
      Parameters:
      - S3BucketBaseName
      - S3DataBucketFolder
      - S3BucketBlockPublicAcls
      - S3BucketBlockPublicPolicy
      - S3BucketIgnorePublicAcls
      - S3BucketRestrictPublicBuckets
  ParameterLabels:
    #################################### Project Name and Environment ##############################
    ProjectName:
      default: "Project Name."
    Environment:
      default: "Environment Name."
    #################################### GitHub Attributes #########################################
    GitHubRef:
      default: "GitHub Ref."
    GitHubURL:
      default: "GitHub URL."
    GitHubWFRunNumber:
      default: "GitHub Workflow Run Number."
    GitHubSHA:
      default: "GitHub SHA"
    GitHubRepository:
      default: "GitHub Repository."
    CiBuild:
      default: "Ci Build."
    StackName:
      default: "Stack Name."
    ################################## KMS Key #######################################################
    KmsMasterKeyAlias: 
      default: "The KMS Master Key Alias To Be Used For Server Side Encryption."
    ################################## S3 Bucket and Folder ######################################
    S3BucketName:
      default: "S3 Bucket Name."
    S3DataBucketFolder:
      default: "The folder(s) to be created."
    S3BucketBlockPublicAcls:
      default: "Allow BlockPublicAcls"
    S3BucketBlockPublicPolicy:
      default: "Allow BlockPublicPolicy"
    S3BucketIgnorePublicAcls:
      default: "Allow IgnorePublicAcls"
    S3BucketRestrictPublicBuckets:
      default: "Allow restrictPublicBuckets"
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: project
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod" 
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  StackName:
    Default: ""
    Description: "The name of the stack which created the resource"
    Type: String  
  ###################################### KMS #######################################################
  KmsMasterKeyAlias:
    Default: "SB-KMS"
    Description: "The KMS Master Key Alias To Be Used For Server Side Encryption."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash."
  ###################################### S3 Bucket and Folder ######################################
  S3BucketBaseName:
    Default: "some-s3-bucket-name-devl-us-east-1"
    Description: "The S3 bucket name for the source data."
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  S3DataBucketFolder:
    Default: "inbound,outbound"
    Description: "The Folder To Be Created For Stroing The Raw Data. Use do_not_create If You Do Not Want To Create Any Folder."
    Type: CommaDelimitedList
    ConstraintDescription: "Should be a comma seperated folder names."  
  S3BucketBlockPublicAcls:
    Default: true
    Description: "Allow Block Public Acls"
    Type: String
    AllowedValues: [true, false]
  S3BucketBlockPublicPolicy:
    Default: true
    Description: "Allow Block Public Policy"
    Type: String
    AllowedValues: [true, false]
  S3BucketIgnorePublicAcls:
    Default: true
    Description: "Allow Ignore Public Acls"
    Type: String
    AllowedValues: [true, false]
  S3BucketRestrictPublicBuckets:
    Default: true
    Description: "Allow Restrict Public Buckets"
    Type: String
    AllowedValues: [true, false]
  S3CustomResourceStackName:
    Default: "s3-custom-resource-stack"
    Description: "S3 Custom Resource Stack Name"
    Type: String
Resources:
  ###################################### S3 Bucket #################################################
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${S3BucketBaseName}-${AWS::AccountId}-${Environment}-${AWS::Region}${CiBuild}'
      BucketEncryption:
          ServerSideEncryptionConfiguration: 
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault: 
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Sub 'alias/${KmsMasterKeyAlias}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: !Ref S3BucketBlockPublicAcls
        BlockPublicPolicy: !Ref S3BucketBlockPublicPolicy
        IgnorePublicAcls: !Ref S3BucketIgnorePublicAcls
        RestrictPublicBuckets: !Ref S3BucketRestrictPublicBuckets
      Tags:
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key:  Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
      - Key: StackName
        Value: !Ref StackName
  S3DataBucketCustomResource:
    Type: Custom::S3CustomResource
    Properties:
      ServiceToken: 
        Fn::ImportValue: !Sub '${S3CustomResourceStackName}-S3CreateFolderCustomResourceLambdaFunctionArn' 
      bucket_name: !Ref S3Bucket
      folders_to_create: !Ref S3DataBucketFolder
Outputs:
  S3BucketArn:
    Description: The endpoint of the S3 integration bucket.
    Value: !GetAtt S3Bucket.Arn
